Add onEnter and onExit events to states
Gray-Wind/StateMachine pull request #1
Opened 2022-02-26 08:24 UTC by Gray-Wind

Those event are present in an android version of the state machine and are missed in iOS version, so it is not possible to use the same logic between platforms.

2022-02-28 11:10 UTC, rusmonster approved these changes

2022-02-28 11:54 UTC, berkus requested changes

2022-02-28 11:54 UTC, berkus commented on Swift/Sources/StateMachine/StateMachine.swift
> +                    onExitActions[stateIdentifier]?()
Transition side-effects happe before you leave the old state? This seems odd.

2022-02-28 11:54 UTC, berkus commented on Swift/Sources/StateMachine/StateMachine.swift
> +                    onEnterActions[state.hashableIdentifier]?()
Or transition side-effects happen after you enter the new state? This also seems odd.

2022-02-28 11:54 UTC, berkus commented on Swift/Sources/StateMachine/StateMachine.swift
> +        fileprivate let event: Event.HashableIdentifier?
`?` is probably a wrong approach here.

```
enum eventType {
  normal(event, action),
  onEnter(() -> Void),
  onExit(() -> Void),
}
```
seems more logical type representation.

2022-02-28 11:54 UTC, berkus commented on Swift/Tests/StateMachineTests/StateMachine_Matter_Tests.swift
> +        case exitSolid
exitedSolid?

2022-03-08 11:09 UTC, berkus requested changes

2022-03-08 11:09 UTC, berkus commented on Swift/Tests/StateMachineTests/StateMachine_Turnstile_Tests.swift
> +        case enterLocked
Make it `entered`/`exited` to match StateMachine_Matter_Tests

2022-03-08 11:09 UTC, berkus commented on Swift/Sources/StateMachine/StateMachine.swift
> +            case onEnter((State) throws -> Void)
```
onEnter(EnterExitAction)
onExit(EnterExitAction) 
```

2022-03-08 11:21 UTC, berkus approved these changes

2022-03-08 11:22 UTC, merged